using System.ComponentModel.DataAnnotations;

namespace CarServiceTracking.UI.Web.ViewModels.Invoices
{
    public class InvoiceCreateVM
    {
        // InvoiceNumber is generated by the API, not required in form
        [StringLength(50, ErrorMessage = "Fatura numarası en fazla 50 karakter olabilir")]
        public string? InvoiceNumber { get; set; }

        [Required(ErrorMessage = "Servis talebi seçimi zorunludur")]
        public int ServiceRequestId { get; set; }

        // InvoiceDate is set by API, not required in form
        [DataType(DataType.Date)]
        public DateTime? InvoiceDate { get; set; }

        // TotalAmount is calculated by API, not required in form
        [Range(0, 999999.99, ErrorMessage = "Toplam tutar 0 ile 999999.99 arasında olmalıdır")]
        public decimal? TotalAmount { get; set; }

        [Range(0, 999999.99, ErrorMessage = "Ödenen tutar 0 ile 999999.99 arasında olmalıdır")]
        public decimal PaidAmount { get; set; }

        [StringLength(1000, ErrorMessage = "Notlar en fazla 1000 karakter olabilir")]
        public string? Notes { get; set; }

        /// <summary>
        /// true ise bu servis talebi için mevcut fatura silinip (soft-delete) yenisi oluşturulur.
        /// </summary>
        [Display(Name = "Mevcut faturayı silip yeniden oluştur")]
        public bool ReplaceIfExists { get; set; }
    }
}
